import Link from "next/link";

export const metadata = {
    title: "Privacy Policy | HNU Clinic",
    description: "Understand how the HNU Clinic platform collects, uses, and protects your information.",
};

export default function PrivacyPage() {
    return (
        <div className="bg-white">
            <section className="bg-linear-to-b from-green-50 via-white to-green-50 px-6 py-16 md:px-12 md:py-24">
                <div className="mx-auto max-w-4xl space-y-12">
                    <div className="space-y-4 text-center md:text-left">
                        <span className="inline-flex items-center rounded-full border border-green-100 bg-white px-3 py-1 text-xs font-semibold uppercase tracking-wide text-green-700">
                            HNU Clinic Privacy Statement
                        </span>
                        <h1 className="text-3xl font-bold text-green-700 md:text-4xl">Privacy Policy</h1>
                        <p className="text-base leading-relaxed text-gray-700 md:text-lg">
                            This Privacy Policy explains how HNU Clinic, the official campus health system of Holy Name University, collects, uses, and safeguards information when you access <span className="font-semibold text-green-700">clinic.hnu.edu</span> or the connected mobile experience.
                        </p>
                    </div>

                    <div className="space-y-10 text-sm leading-relaxed text-gray-700 md:text-base">
                        <section className="space-y-3">
                            <h2 className="text-xl font-semibold text-green-700">Information we collect</h2>
                            <p>
                                When you sign in with Google, we receive your Holy Name University email address and profile name. If you contact us or submit forms, we collect the information you provide in order to respond.
                            </p>
                            <p>
                                Within the clinic portal we store appointment details, consultation notes, and uploaded medical records provided by you or generated by clinic staff.
                            </p>
                        </section>

                        <section className="space-y-3">
                            <h2 className="text-xl font-semibold text-green-700">How we use your information</h2>
                            <ul className="list-disc space-y-2 pl-6">
                                <li>Authenticate students, faculty, and staff using institutional Google accounts.</li>
                                <li>Coordinate appointments, notifications, and follow-up care with the appropriate medical team.</li>
                                <li>Maintain accurate health records for continuity of care within HNU Clinic.</li>
                                <li>Respond to support inquiries you send through our contact channels.</li>
                            </ul>
                        </section>

                        <section className="space-y-3">
                            <h2 className="text-xl font-semibold text-green-700">Data retention and control</h2>
                            <p>
                                Clinic records are retained according to the Holy Name University health services retention schedule. You may request corrections by contacting the clinic desk or emailing <Link href="mailto:clinic-support@hnu.edu" className="font-medium text-green-700 underline underline-offset-2">clinic-support@hnu.edu</Link>.
                            </p>
                            <p>
                                If you wish to revoke Google access, remove your authorized session from your Google account settings and notify the clinic so we can deactivate your portal login.
                            </p>
                        </section>

                        <section className="space-y-3">
                            <h2 className="text-xl font-semibold text-green-700">Security practices</h2>
                            <p>
                                HNU Clinic encrypts information in transit and at rest. Access to records is restricted to authorized medical staff and audited to ensure compliance with institutional policies.
                            </p>
                            <p>
                                The application is hosted on infrastructure managed by Holy Name University and served exclusively from the verified domain <span className="font-semibold text-green-700">clinic.hnu.edu</span>.
                            </p>
                        </section>

                        <section className="space-y-3">
                            <h2 className="text-xl font-semibold text-green-700">Contact us</h2>
                            <p>
                                If you have questions about this policy or our data practices, please email <Link href="mailto:clinic-support@hnu.edu" className="font-medium text-green-700 underline underline-offset-2">clinic-support@hnu.edu</Link> or visit the clinic office at Holy Name University Main Campus.
                            </p>
                        </section>
                    </div>

                    <p className="text-xs text-gray-500">
                        Effective date: {new Date().getFullYear()}.
                    </p>
                </div>
            </section>
        </div>
    );
}
